systemProp.sonar.host.url=
systemProp.sonar.projectName=
systemProp.sonar.projectKey=
systemProp.sonar.sourceEncoding=utf-8
systemProp.sonar.language=java
systemProp.sonar.java.source=11
coreversion = 3.3
# nexus
atMavenGroupUrl=https://nexus-internal.headoffice.psbank.local/repository/at-maven-group/
mvnProxyUrl=https://nexus-external.psbnk.msk.ru/repository/maven-public/

lombokVersion=1.18.22
#systemProp.javax.net.ssl.trustStore=/jre-11.0.14.1-full/lib/security/jssecacerts